version: "3.9"
services:
  #scraper:
  #  container_name: scraper
  #  image: godfriedmeesters/scraper:latest
  #  volumes:
  #    - ./logs:/usr/src/app/logs
  controller:
    container_name: controller
    image: godfriedmeesters/controller:latest
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - CRON=*/5 * * * *
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.10.1
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/usr/share/filebeat/logs
  watchtower:
    container_name: watchtower
    image: index.docker.io/containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./watchtower-config.json:/config.json
